# Generated by Django 4.2.21 on 2025-06-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporte',
            name='data_aporte',
            field=models.DateField(),
        ),
    ]
