# Generated by Django 5.1.7 on 2025-03-24 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortek', '0002_editora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_comentario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Criptoativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cripto_sigla', models.CharField(max_length=10)),
                ('Criptoativo', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Criptoativo_adq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant_adq', models.DecimalField(decimal_places=5, max_digits=10)),
                ('cripto_sigla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cripto_siglas', to='vortek.criptoativo')),
                ('criptoativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criptoativos', to='vortek.criptoativo')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valors', to='vortek.criptoativo')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_noticia', models.CharField(max_length=100)),
                ('conteudo_noticia', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Editora',
        ),
    ]
