# Generated by Django 5.1.7 on 2025-03-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortek', '0003_comentario_criptoativo_criptoativo_adq_noticia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criptoativo',
            name='valor',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='criptoativo_adq',
            name='quant_adq',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
