# Generated by Django 5.1.7 on 2025-03-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortek', '0006_alter_criptoativo_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criptoativo',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='criptoativo_adq',
            name='quant_adq',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
