# Generated by Django 5.1.7 on 2025-05-11 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortek', '0008_alter_criptoativo_valor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aporte', models.DateField(auto_now_add=True)),
                ('valor_aportado', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantidade', models.DecimalField(decimal_places=8, max_digits=10)),
                ('criptoativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vortek.criptoativo')),
            ],
        ),
    ]
